const ActionTypes = {
    SET_LOGIN_STATUS : "SET_LOGIN_STATUS",
    SET_CURRENT_ACCESS : "SET_CURRENT_ACCESS",
    NEW_ROW_UPDATE : "NEW_ROW_UPDATE",
    SET_CURRENT_TABLE : "SET_CURRENT_TABLE",
    SET_MEAL_DATA : "SET_MEAL_DATA",
    SET_USER_DATA : "SET_USER_DATA",
    SET_EXPECTED_DATA : 'SET_EXPECTED_DATA',
    RESET : "RESET",
};

export default ActionTypes;
